version: "3.8"

services:
  database:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - cv_helper_network


volumes:
  database_data:
    driver: local
networks:
  cv_helper_network:
    driver: bridge
